### ISSUE TITLE
Linking of project does not work [android] / [iOS]

### ISSUE THREAD

**Issue by gorjanz** [remobile/react-native-file-transfer#2]
When I try to use this module, and build the app for the android platform, I get the following error:

FAILURE: Build failed with an exception.
- Where:
  Build file '/Users/gzajkovs/Workspace/seminar-app/node_modules/@remobile/react-native-file-transfer/android/build.gradle' line: 25
- What went wrong:
  A problem occurred evaluating project ':react-native-file-transfer'.
  
  > Project with path ':react-native-cordova' could not be found in project ':react-native-file-transfer'.

On iOS, there is the following error:
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_CDVInvokedUrlCommand", referenced from:
      objc-class-ref in libRCTFileTransfer.a(CDVFileTransfer.o)
  "_OBJC_CLASS_$_CDVPlugin", referenced from:
      _OBJC_CLASS_$_CDVFileTransfer in libRCTFileTransfer.a(CDVFileTransfer.o)
  "_OBJC_CLASS_$_CDVPluginResult", referenced from:
      objc-class-ref in libRCTFileTransfer.a(CDVFileTransfer.o)
  "_OBJC_METACLASS_$_CDVPlugin", referenced from:
      _OBJC_METACLASS_$_CDVFileTransfer in libRCTFileTransfer.a(CDVFileTransfer.o)

**Comment by happyEgg** [comment]
@gorjanz In you project settings.gradle!!
you add project(':react-native-cordova').projectDir = new File(rootProject.projectDir, '../node_modules/@remobile/react-native-cordova/android')

**Comment by nlindroos** [comment]
@gorjanz What is not mentioned in https://github.com/remobile/react-native-file-transfer/blob/master/README.md is that @remobile/react-native-cordova is a requirement for @remobile/react-native-file-transfer.

To enable @remobile/react-native-file-transfer, in addition to the steps mentioned in the readme:
1. run `npm i --save @remobile/react-native-cordova`,
2. add

```
include ':react-native-cordova'
project(':react-native-cordova').projectDir = new File(rootProject.projectDir, '../node_modules/@remobile/react-native-cordova/android')
```

to your main project's settings.gradle file.
